// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Control.tsx";
import * as $$1 from "./islands/Controls.tsx";
import * as $$2 from "./islands/EditorArea.tsx";
import * as $$3 from "./islands/Footer.tsx";
import * as $$4 from "./islands/SizeList.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Control.tsx": $$0,
    "./islands/Controls.tsx": $$1,
    "./islands/EditorArea.tsx": $$2,
    "./islands/Footer.tsx": $$3,
    "./islands/SizeList.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
